server:
  port: 9000
spring:
  application:
    name: scw-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
    static-path-pattern: /resources/**
  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true

oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  bucketName: scwoss20230904
  path: pic/